// GENERATED by tools/sprite_pipeline/gen_character_catalog.py — do not edit by hand.
// Seeded from the cast manifests. Rerun the generator when the cast changes.
//
// Tier is authoritative only for legendaries (marked in the manifest); all other
// tiers are DEFAULTED to novice (tierIsDefaulted: true) pending the cast-scope doc.

import 'character_definition.dart';
import 'enums.dart';

const Map<String, CharacterDefinition> characterCatalog = {
  'anwen': CharacterDefinition(id: 'anwen', displayName: 'Anwen Starling', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'armand': CharacterDefinition(id: 'armand', displayName: 'Ser Armand Lowfield', tier: AdventurerTier.legendary),
  'asha': CharacterDefinition(id: 'asha', displayName: 'Asha Brightcoin', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'bessa': CharacterDefinition(id: 'bessa', displayName: 'Bessa', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'borrin': CharacterDefinition(id: 'borrin', displayName: 'Borrin Chapelback', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'bren': CharacterDefinition(id: 'bren', displayName: 'Bren Ashboot', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'brindle': CharacterDefinition(id: 'brindle', displayName: 'Brindle Mosscap', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'caldus': CharacterDefinition(id: 'caldus', displayName: 'Caldus Vey', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'cricket': CharacterDefinition(id: 'cricket', displayName: 'Cricket Lowbell', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'della': CharacterDefinition(id: 'della', displayName: 'Della Truepin', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'durnik': CharacterDefinition(id: 'durnik', displayName: 'Durnik Saltbeard', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'elowen': CharacterDefinition(id: 'elowen', displayName: 'Elowen', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'fenwick': CharacterDefinition(id: 'fenwick', displayName: 'Fenwick Grays', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'halra': CharacterDefinition(id: 'halra', displayName: 'Halra Greenwake', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'harp': CharacterDefinition(id: 'harp', displayName: 'Harp Vey', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'ilyra': CharacterDefinition(id: 'ilyra', displayName: 'Ilyra Moonstep', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'isolde': CharacterDefinition(id: 'isolde', displayName: 'Isolde Fenrice', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'jessa': CharacterDefinition(id: 'jessa', displayName: 'Jessa Briarheel', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'keebo': CharacterDefinition(id: 'keebo', displayName: 'Keebo Clatterpin', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'korrin': CharacterDefinition(id: 'korrin', displayName: 'Korrin', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'lethren': CharacterDefinition(id: 'lethren', displayName: 'Lethren of the Blue Road', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'maelis': CharacterDefinition(id: 'maelis', displayName: 'Maelis Sunreed', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'mara': CharacterDefinition(id: 'mara', displayName: 'Mara', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'mink': CharacterDefinition(id: 'mink', displayName: 'Mink Bottlecap', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'mirelle': CharacterDefinition(id: 'mirelle', displayName: 'Mirelle Crowglass', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'mothervarr': CharacterDefinition(id: 'mothervarr', displayName: 'Mother Varr', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'nym': CharacterDefinition(id: 'nym', displayName: 'Nym', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'oren': CharacterDefinition(id: 'oren', displayName: 'Oren', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'orla': CharacterDefinition(id: 'orla', displayName: 'Orla Mourn', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'pip': CharacterDefinition(id: 'pip', displayName: 'Pip Glimmerlock', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'quorra': CharacterDefinition(id: 'quorra', displayName: 'Quorra Brightscale', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'ralgar': CharacterDefinition(id: 'ralgar', displayName: 'Ralgar One-Mitt', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'renn': CharacterDefinition(id: 'renn', displayName: 'Old Renn Tallow', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'rook': CharacterDefinition(id: 'rook', displayName: 'Rook', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'saela': CharacterDefinition(id: 'saela', displayName: 'Saela Thornmere', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'sera': CharacterDefinition(id: 'sera', displayName: 'Sera', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'shavarra': CharacterDefinition(id: 'shavarra', displayName: 'Shavarra Duskwell', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'silt': CharacterDefinition(id: 'silt', displayName: 'Silt of Three Roads', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'syl': CharacterDefinition(id: 'syl', displayName: 'Syl Nighthollow', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'tavi': CharacterDefinition(id: 'tavi', displayName: 'Tavi', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'thane': CharacterDefinition(id: 'thane', displayName: 'Thane Grudgebell', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'torv': CharacterDefinition(id: 'torv', displayName: 'Torv Emberjaw', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'vaelor': CharacterDefinition(id: 'vaelor', displayName: 'Vaelor Brass-Scale', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'vellum': CharacterDefinition(id: 'vellum', displayName: 'Vellum Quince', tier: AdventurerTier.novice, tierIsDefaulted: true),
  'ysabet': CharacterDefinition(id: 'ysabet', displayName: 'Ysabet Crowglass', tier: AdventurerTier.legendary),
};
