"""
Generate lib/src/domain/character_catalog.dart from the cast manifests.

Seeds one CharacterDefinition per manifest keeper: id = target filename stem
without the char_ prefix (char_korrin.png -> 'korrin'); displayName = the
manifest Character cell (with any *(Legendary)* marker stripped); tier =
legendary if the cell is marked legendary, else novice (defaulted, flagged).

Re-runnable: rerun when the cast grows. Usage:
  python gen_character_catalog.py --out <dart_file> <manifest.md> [<manifest.md> ...]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

UUID_RE = re.compile(
    r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)
LEGENDARY_RE = re.compile(r"\(\s*legendary\s*\)", re.IGNORECASE)


def parse(manifest: Path):
    rows = []
    for line in manifest.read_text(encoding="utf-8").splitlines():
        if not line.lstrip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        target = next((c for c in cells if c.lower().endswith(".png")
                       and c.lower().startswith("char_")), None)
        has_uuid = any(UUID_RE.fullmatch(c) for c in cells)
        if not target or not has_uuid:
            continue
        char_id = target[len("char_"):-len(".png")].lower()
        legendary = bool(LEGENDARY_RE.search(cells[0]))
        display = LEGENDARY_RE.sub("", cells[0]).replace("*", "").strip()
        rows.append((char_id, display, legendary))
    return rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("manifests", nargs="+")
    args = ap.parse_args()

    seen, rows = set(), []
    for m in args.manifests:
        for char_id, display, legendary in parse(Path(m)):
            if char_id in seen:
                continue
            seen.add(char_id)
            rows.append((char_id, display, legendary))
    rows.sort(key=lambda r: r[0])

    lines = [
        "// GENERATED by tools/sprite_pipeline/gen_character_catalog.py — do not edit by hand.",
        "// Seeded from the cast manifests. Rerun the generator when the cast changes.",
        "//",
        "// Tier is authoritative only for legendaries (marked in the manifest); all other",
        "// tiers are DEFAULTED to novice (tierIsDefaulted: true) pending the cast-scope doc.",
        "",
        "import 'character_definition.dart';",
        "import 'enums.dart';",
        "",
        "const Map<String, CharacterDefinition> characterCatalog = {",
    ]
    for char_id, display, legendary in rows:
        tier = "AdventurerTier.legendary" if legendary else "AdventurerTier.novice"
        defaulted = "" if legendary else ", tierIsDefaulted: true"
        safe = display.replace("'", r"\'")
        lines.append(
            f"  '{char_id}': CharacterDefinition(id: '{char_id}', "
            f"displayName: '{safe}', tier: {tier}{defaulted}),"
        )
    lines += ["};", ""]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} CharacterDefinition entries -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
